name: GlueTransPia PR Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  lint-sh:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0

  pr-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build env and run tests
      run: make test