name: GlueTrans PR Check against supported Gluetun versions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize
  workflow_dispatch:

env:
  GLUETRANS_VPN_USERNAME: ${{ secrets.GLUETRANS_VPN_USERNAME }}
  GLUETRANS_VPN_PASSWORD: ${{ secrets.GLUETRANS_VPN_PASSWORD }}
  GLUETRANS_VPN_REGIONS: ${{ secrets.GLUETRANS_VPN_REGIONS }}
  GLUETRANS_TRANSMISSION_USERNAME: ${{ secrets.GLUETRANS_TRANSMISSION_USERNAME }}
  GLUETRANS_TRANSMISSION_PASSWORD: ${{ secrets.GLUETRANS_TRANSMISSION_PASSWORD }}
  GLUETRANS_SONAR_ORGANIZATION: ${{ secrets.GLUETRANS_SONAR_ORGANIZATION }}
  GLUETRANS_SONAR_PROJECT_KEY: ${{ secrets.GLUETRANS_SONAR_PROJECT_KEY }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  lint-sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@2.0.0

  pr-check-gluetun-v3_36:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build env and run tests
      run: make GLUETUN_VERSION=v3.36 pr-test

  pr-check-gluetun-v3_37:
    needs: pr-check-gluetun-v3_36
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build env and run tests
      run: make GLUETUN_VERSION=v3.37 pr-test

  pr-check-gluetun-v3_37_1:
    needs: pr-check-gluetun-v3_37
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build env and run tests
      run: make GLUETUN_VERSION=v3.37.1 pr-test

  pr-check-gluetun-v3_38:
    needs: pr-check-gluetun-v3_37_1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build env and run tests
      run: make GLUETUN_VERSION=v3.38 pr-test

  pr-check-gluetun-v3_38_1:
    needs: pr-check-gluetun-v3_38
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build env and run tests
      run: make GLUETUN_VERSION=v3.38.1 pr-test

  pr-check-gluetun-v3_39:
    needs: pr-check-gluetun-v3_38_1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build env and run tests
      run: make GLUETUN_VERSION=v3.39 pr-test

  pr-check-gluetun-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build env and run tests
      run: make GLUETUN_VERSION=latest pr-test
